version: "3.0"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    depends_on:
      - mongo
  doorman:
    image: feedkitchen/doorman
    build:
      context: ../src/
      dockerfile: FeedKitchen.Doorman/dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  chefportal:
    image: feedkitchen/chefportal
    build:
      context: ../src/
      dockerfile: FeedKitchen.ChefPortal/dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongo
      - doorman
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_SERVER
      - MONGODB_DATABASE
  cookportal:
    image: feedkitchen/cookportal
    build:
      context: ../src/
      dockerfile: FeedKitchen.CookPortal/dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - mongo
      - doorman
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_SERVER
      - MONGODB_DATABASE
  ingredientsbuyer:
    image: feedkitchen/ingredientsbuyer
    build:
      context: ../src/
      dockerfile: FeedKitchen.IngredientsBuyer/dockerfile
    depends_on:
      - mongo
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_SERVER
      - MONGODB_DATABASE
  menuwaiter:
    image: feedkitchen/menuwaiter
    build:
      context: ../src/
      dockerfile: FeedKitchen.MenuWaiter/dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_SERVER
      - MONGODB_DATABASE
