version: "3.0"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    depends_on:
      - mongo
  chefportal:
    image: feedkitchen/chefportal
    build:
      context: ../src/FeedKitchen.ChefPortal/
    ports:
      - "5003:5001"
    depends_on:
      - mongo
  cookportal:
    image: feedkitchen/cookportal
    build:
      context: ../src/FeedKitchen.CookPortal/
    ports:
      - "5002:5001"
    depends_on:
      - mongo
  ingredientsbuyer:
    image: feedkitchen/ingredientsbuyer
    build:
      context: ../src/FeedKitchen.IngredientsBuyer/
    depends_on:
      - mongo
  menuwaiter:
    image: feedkitchen/menuwaiter
    build:
      context: ../src/FeedKitchen.MenuWaiter/
    ports:
      - "5001:5001"
    depends_on:
      - mongo
